apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- namespace.yaml

patches:
- path: ingress-patch.yaml

images:
- name: chat-front
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-front
  newTag: 81676e0d25ea86e57fbd5a6bec501f600526f56c
- name: chat-svc
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-svc
  newTag: 81676e0d25ea86e57fbd5a6bec501f600526f56c
