apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- namespace.yaml

patches:
- path: ingress-patch.yaml
- patch: |-
    - op: replace
      path: /data/config-docker.yml
      value: |
        pyms:
          services:
            requests:
              data: ""
          config:
            DEBUG: true
            TESTING: true
            APP_NAME: project
            APPLICATION_ROOT : /
            SECRET_KEY: "gjr39dkjn344_!67#"
            service_host: https://staging.atiqabubakar.sbs
  target:
    kind: ConfigMap
    name: chat-front-config

images:
- name: chat-front
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-front
  newTag: cd554df749d504aa50f0ab7b28dd1d09463dc598
- name: chat-svc
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-svc
  newTag: cd554df749d504aa50f0ab7b28dd1d09463dc598
