apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- namespace.yaml

patches:
- path: ingress-patch.yaml
- patch: |-
    - op: replace
      path: /data/config-docker.yml
      value: |
        pyms:
          services:
            requests:
              data: ""
          config:
            DEBUG: true
            TESTING: true
            APP_NAME: project
            APPLICATION_ROOT : /
            SECRET_KEY: "gjr39dkjn344_!67#"
            service_host: https://chat.atiqabubakar.sbs
  target:
    kind: ConfigMap
    name: chat-front-config
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: chat-front
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: chat-svc

images:
- name: chat-front
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-front
  newTag: 81676e0d25ea86e57fbd5a6bec501f600526f56c
- name: chat-svc
  newName: 454448876799.dkr.ecr.us-east-1.amazonaws.com/chat-svc
  newTag: 81676e0d25ea86e57fbd5a6bec501f600526f56c
