apiVersion: v1
kind: Secret
metadata:
  name: chat-db-secret
  labels:
    app: chat-db
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "super_secret_root_password"
  MYSQL_DATABASE: "abudb"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "database_password"
