apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: solo-devops-rds-secret # Replace with actual secret name
        property: host
    - secretKey: username
      remoteRef:
        key: solo-devops-rds-secret
        property: username
    - secretKey: password
      remoteRef:
        key: solo-devops-rds-secret
        property: password
    - secretKey: dbname
      remoteRef:
        key: solo-devops-rds-secret
        property: dbname
