apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - chat-front-deployment.yaml
  - chat-front-service.yaml
  - chat-svc-deployment.yaml
  - chat-svc-service.yaml
  - ingress.yaml
  - external-secret.yaml
